[project]
name = "dbt-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-bigquery>=1.9.0",
    "dbt-core<=1.8.9",
    "dlt>=1.5.0",
    "logbook",
]
